resource_group_name      = "jjmicroservices-rg"
resource_group_node_name = "jjmicroservices-aks-rg"
cluster_name             = "jjaks"
aad_aks_admin_role       = "ee2529f7-8f82-450a-9cd5-53968fff8c5d"
ingress_load_balancer_ip = "10.4.2.250"
keyvault_name            = "jjakskv"
keyvault_rg              = "jjmicroservices-rg"
acr_name                 = "jjakscontainers"
acr_rg                   = "jjmicroservices-rg"

