resource_group_name = "jjmicroservices-test-rg"
resource_group_node_name = "jjmicroservices-test-aks-rg"
cluster_name = "jjakstest"
cluster_windows_username = "cloudadmin"
cluster_windows_password = "heslo-123"
aad_aks_admin_role = "ee2529f7-8f82-450a-9cd5-53968fff8c5d"
ingress_load_balancer_ip = "10.4.2.251"
keyvault_name = "jjkeyvault"
keyvault_rg = "jjdevmanagement"

