name: 'jjaks-terraform'

on:  
  workflow_dispatch:  
#  push:
#    branches:
#    - master    
#  pull_request:
#    branches:
#    - main
    
jobs:
  terraform:
    name: 'Terraform deployment'
    runs-on: ubuntu-latest
    environment: production
    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}

    defaults:
      run:
        shell: bash
        working-directory: src-jjaks

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1     

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: ${{ (github.ref == 'refs/heads/master' && github.event_name == 'push') || (github.event_name == 'workflow_dispatch') }}
      run: terraform apply -auto-approve

    - name: Terraform Output
      run: terraform output kube_config_raw