name: federatedIdentityDemo

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Azure Login
        uses: Azure/login@v1.4.3
        with:
          client-id: 9dd430a4-4204-4c1e-b40d-414155e3230c
          tenant-id: 3e57d8e7-0aab-4374-a965-7a968fc4ec78
          subscription-id: eb1d6021-9f80-4613-b383-2bd8c4d31f09
          
      - name: Test
        run: az group list -o table