name: federatedIdentityDemo

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: OIDC Login to Azure Public Cloud
        uses: Azure/login@v1.4.3
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
        # using User Managed Identity and Federated credentials
        # https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure
      - name: Test
        run: az group list -o table